# Generated by Django 3.1.6 on 2021-02-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('Discount_Price', models.FloatField()),
                ('Category', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Image', models.CharField(max_length=200)),
            ],
        ),
    ]
